DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(550) NOT NULL,
  author VARCHAR(50) NOT NULL,
  type VARCHAR(50) NOT NULL,
  price INT NOT NULL,
  isbn VARCHAR(250) NOT NULL
  --  ,promocode VARCHAR(150)
);

INSERT INTO BOOK (id, name, description, author, type, price, isbn) VALUES
  (1, 'book1', 'book1', 'KPT', 1, 100, 'isbn-1');

DROP TABLE IF EXISTS PROMOCODE;

CREATE TABLE PROMOCODE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    promocode VARCHAR(10) NOT NULL
);

INSERT INTO PROMOCODE (ID, PROMOCODE)  VALUES (1, 'FLASH-10');

DROP TABLE IF EXISTS PROMOCODE_DETAILS;

CREATE TABLE PROMOCODE_DETAILS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    promocodeid INT(10) NOT NULL,
    type VARCHAR(50) NOT NULL,
    discountpct VARCHAR(10) NOT NULL
);

INSERT INTO PROMOCODE_DETAILS (id, promocodeid, type, discountpct)  VALUES (1, 1, 'FICTION', 12);
INSERT INTO PROMOCODE_DETAILS (id, promocodeid, type, discountpct)  VALUES (2, 1, 'COMIC', 12);